@startuml


(ectyper \ncommandline) as ectyper
:Third Party App: as 3rd
:User: -> [Galaxy]
[Galaxy] --> :User:
:User: --> ectyper : "\nvia REST API\n or local machine"
3rd --> ectyper : "via REST API"
Galaxy -> ectyper
(ectyper) --> Galaxy

package JSON {
    (ectyper) --> JSON
}

package TSV{
    (ectyper) --> TSV
}

JSON --> [Galaxy]
JSON --> 3rd
TSV --> :User:



'(Use the application) as (Use)
'
'User -> (Start)
'User --> (Use)
'
'Galaxy ---> (Use)

'note right of Galaxy : This is an example.
'
'note right of (Use)
'A note can also
'be on several lines
'end note
'
'note "This note is connected\nto several objects." as N2
'(Start) .. N2
'N2 .. (Use)

@enduml