about:
    license: MIT
    summary: Ectyper is a python script for serotyping e.coli genomes
    author: Camille La Rose, Chad Laing, Sam Sung
    home: https://github.com/phac-nml/ecoli_serotyping

package:
    name: ectyper
    version: 0.0.9

source:
    path: ../../

build:
  script: python setup.py install

requirements:
    build:
        - python >=2.7,<3|>=3.3,{{PY_VER}}*
        - future
        - backports.weakref # [py27]
    run:
        - python {{PY_VER}}*
        - future
        - backports.weakref # [py27]
        - pandas >=0.21.1.*
        - samtools >=1.5.*
        - bowtie2 >=2.3.0.*
        - mash >=1.1.*
        - bcftools >=1.6.*
        - biopython >=1.68.*
        - blast >=2.2.31.*
        - seqtk >=1.2.*
        - subprocess32 >=3.5.0 # [py27]
test:
    requires: # note: our travis env is defined in .travis.yml, not here.
        - backports.weakref # [py27]
        - future
        - subprocess32 >=3.5.0 # [py27]
    commands:
        - ectyper -h
